
FROM fluentd:v1.14-1


USER root


RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
&& gem uninstall -I elasticsearch \
&& gem install elasticsearch -v 7.17.0 \
&& sudo gem install fluent-plugin-elasticsearch \
&& sudo gem sources --clear-all \
&& apk del .build-deps \
&& rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem


COPY ./conf/fluent.conf /fluentd/etc/

COPY entrypoint.sh /bin/

RUN chmod +x /bin/entrypoint.sh

USER fluent