version: "3"

networks:
  my-network:
    driver: bridge
services:

  fluentd: 
    build: ./fluentd
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: 
      - "24224:24224"
    networks:
      - my-network      
  elasticsearch:
    image: elasticsearch:7.17.0
    ports: 
      - "9200:9200"
    networks:
      - my-network      
    environment:
      - discovery.type=single-node 
    volumes: 
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.17.0
    links: 
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: 
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
        ELASTICSEARCH_HOSTS=elasticsearch:9200
    networks:
      - my-network      
volumes:
  esdata:
