version: "3"
networks:
  my-network:
    driver: bridge
services:
  fluentd: 
    build: .
    volumes:
      - ./:/fluentd/etc/
    network_mode: 'host' 
  coupon-pf:
    image: 341433527940.dkr.ecr.ap-northeast-1.amazonaws.com/coupon-pf:1378
    environment:
      NODE_ENV: development   
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: coupon.log       
    network_mode: 'host'   
    depends_on:
      - fluentd
